/**
 * @file src/assets/SLM_206_v4.h
 * @brief Declarations for the generated SLM_206 font asset used by the UI.
 *
 * @details Documentation is intentionally concise and interface-oriented so
 * the source can support future DO-178C planning artifacts.
 */

#ifndef SLM_206_V4_H
#define SLM_206_V4_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

/* Background image descriptor generated by LVGL image converter.
 * Defined in SLM_206_v4.c
 */
extern const lv_image_dsc_t SLM_206_v4;

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* SLM_206_V4_H */
